[package]
name = "fish-common"
edition.workspace = true
rust-version.workspace = true
version = "0.0.0"
repository.workspace = true
license.workspace = true

[dependencies]
libc.workspace = true
nix.workspace = true
once_cell.workspace = true

[lints]
workspace = true
